### ISSUE TITLE
Blender-Flowmap-Tools

### ISSUE THREAD

**Issue by andrehunter** [isathar/Blender-Flowmap-Tools#1]
Blender-Flowmap-Tools :Allows the use of flowmaps in your BGE

**Comment by KenzieMac130** [comment]
You could write a GLSL shader for flowmapping. Or a BI node graph for it. (I personally would aim to move away from the BGE as I think it might be replaced later in the 2.8+ releases of blender. There's not much development on it anymore. And with Unity 5 and UE4 going free and even the recent rewrites in Ogre I would personally jump ship.)

**Comment by isathar** [comment]
The point of the addon is to create flowmaps that can be used in shaders/materials in your engine of choice, so extending it to allow use in BGE is outside of its scope. Besides, I'm not sure if there's a hardware/software combination that can manipulate a 3D vector field piecewise and still have room to run anything else in real-time.
